### ISSUE TITLE
[tracking] Consolidate go-bindata forks

### ISSUE THREAD

**Issue by vielmetti** [a-urth/go-bindata#1]
This is one of several forks of go-bindata. It would be good and useful for the Go community to bring those forks back together, perhaps under a new name, to minimize the impact of the deletion and uncertain recreation of the original repo.

Commentary
* [ ]  [Reddit /r/golang](https://www.reddit.com/r/golang/comments/7vv9zz/popular_lib_gobindata_removed_from_github_or_why/)

Alternative projects (don't use go-bindata)

* [ ] https://github.com/gobuffalo/packr
* [ ] https://github.com/rakyll/statik

Related issues and repos (forks of go-bindata)

* [ ] https://github.com/avelino/awesome-go/pull/1675
* [ ] https://github.com/jteeuwen/go-bindata/issues/3
* [ ] https://github.com/jteeuwen/go-bindata/issues/5
* [ ] https://github.com/tmthrgd/go-bindata
* [ ] https://github.com/shuLhan/go-bindata
* [ ] https://github.com/containus/go-bindata

Related downstream repos (consume upstream go-bindata)

* [ ] https://packages.debian.org/sid/go-bindata
* [ ] https://www.npmjs.com/package/go-bindata

Package and dependency management in Go

* [ ] https://github.com/whyrusleeping/gx/issues/141 (gx)
* [ ] https://github.com/golang/dep (dep)

Systems that have been impacted by this (many)

* [ ] https://github.com/rook/rook/issues/1478

**Comment by vielmetti** [comment]
add link to awesome-go list discussion

**Comment by liweiv** [comment]
https://github.com/go-bindata/go-bindata
